framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  #http_method_override: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    enabled: true
    cookie_secure: auto
    cookie_samesite: lax
    cookie_lifetime: 172800
    gc_maxlifetime: 172800
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions'
  #esi: true
  #fragments: true
  php_errors:
    log: true
